### ISSUE TITLE
vercel部署错误

### ISSUE THREAD

**Issue by shixiaocaia** [Ice-Hazymoon/hugo-theme-luna#101]
使用了主题下的vercel.json部署时，出现如下错误，同时检查了vercel Build & Development Settings也是一致的，不知道为什么缺失tailwindcss，如果有空的话，麻烦帮忙检查下，谢谢

![image](https://github.com/Ice-Hazymoon/hugo-theme-luna/assets/68102662/97d02309-6595-40b3-ab9b-d737d6ad1350)

**Comment by Ice-Hazymoon** [comment]
麻烦日志再提供详细一些

**Comment by shixiaocaia** [comment]
[09:18:19.527] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[09:18:19.633] Cloning github.com/shixiaocaia/Hugo-luna-mod (Branch: test, Commit: d9e0a38)
[09:18:19.974] Previous build cache not available
[09:18:21.046] Cloning completed: 1.413s
[09:18:21.487] Running "vercel build"
[09:18:21.923] Vercel CLI 32.3.1
[09:18:22.647] Installing Hugo version 0.104.3
[09:18:23.339] Running "install" command: `cd themes/hugo-theme-luna && npm install postcss-cli -g && npm install --production && cd ../../`...
[09:18:25.856] 
[09:18:25.856] added 65 packages in 2s
[09:18:25.856] 
[09:18:25.856] 14 packages are looking for funding
[09:18:25.857]   run `npm fund` for details
[09:18:26.087] npm WARN config production Use `--omit=dev` instead.
[09:18:44.587] 
[09:18:44.587] added 256 packages, and audited 257 packages in 19s
[09:18:44.587] 
[09:18:44.587] 85 packages are looking for funding
[09:18:44.587]   run `npm fund` for details
[09:18:44.588] 
[09:18:44.589] found 0 vulnerabilities
[09:18:44.683] Start building sites … 
[09:18:44.684] hugo v0.104.3-58b824581360148f2d91f5cc83f69bd22c1aa331+extended linux/amd64 BuildDate=2022-10-04T14:25:23Z VendorInfo=gohugoio
[09:18:44.684] INFO 2023/09/27 01:18:44 removing all files from destination that don't exist in static dirs
[09:18:44.684] INFO 2023/09/27 01:18:44 syncing static files to /
[09:18:45.055] INFO 2023/09/27 01:18:45 postcss: use config file /vercel/path0/postcss.config.js
[09:18:45.665] INFO 2023/09/27 01:18:45 postcss: Error: Cannot find module 'tailwindcss'
[09:18:45.665] Require stack:
[09:18:45.665] - /vercel/path0/postcss.config.js
[09:18:45.665]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[09:18:45.666]     at Module._load (node:internal/modules/cjs/loader:922:27)
[09:18:45.666]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[09:18:45.666]     at require (node:internal/modules/cjs/helpers:121:18)
[09:18:45.666]     at Object.<anonymous> (/vercel/path0/postcss.config.js:6:9)
[09:18:45.666]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[09:18:45.666]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[09:18:45.666]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[09:18:45.666]     at Module._load (node:internal/modules/cjs/loader:960:12)
[09:18:45.666]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
[09:18:45.666]   code: 'MODULE_NOT_FOUND',
[09:18:45.666]   requireStack: [ '/vercel/path0/postcss.config.js' ]
[09:18:45.666] }
[09:18:45.669] INFO 2023/09/27 01:18:45 postcss: npm notice 
[09:18:45.670] npm 
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss: notice
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss:  New major version of npm available! 9.6.7 -> 10.1.0
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss: npm
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss:  
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss: notice
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss:  Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
[09:18:45.670] npm
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss:  
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss: notice
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss:  Run `npm install -g npm@10.1.0` to update!
[09:18:45.670] npm notice
[09:18:45.670] INFO 2023/09/27 01:18:45 postcss:  
[09:18:45.697] Error: Error building site: POSTCSS: failed to transform "main.css" (text/css): Error: Cannot find module 'tailwindcss'
[09:18:45.697] Require stack:
[09:18:45.697] - /vercel/path0/postcss.config.js
[09:18:45.697]     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
[09:18:45.697]     at Module._load (node:internal/modules/cjs/loader:922:27)
[09:18:45.697]     at Module.require (node:internal/modules/cjs/loader:1143:19)
[09:18:45.698]     at require (node:internal/modules/cjs/helpers:121:18)
[09:18:45.698]     at Object.<anonymous> (/vercel/path0/postcss.config.js:6:9)
[09:18:45.698]     at Module._compile (node:internal/modules/cjs/loader:1256:14)
[09:18:45.698]     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
[09:18:45.698]     at Module.load (node:internal/modules/cjs/loader:1119:32)
[09:18:45.698]     at Module._load (node:internal/modules/cjs/loader:960:12)
[09:18:45.698]     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29) {
[09:18:45.698]   code: 'MODULE_NOT_FOUND',
[09:18:45.698]   requireStack: [ '/vercel/path0/postcss.config.js' ]
[09:18:45.698] }
[09:18:45.698] npm notice 
[09:18:45.698] npm notice New major version of npm available! 9.6.7 -> 10.1.0
[09:18:45.699] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
[09:18:45.699] npm notice Run `npm install -g npm@10.1.0` to update!
[09:18:45.699] npm notice
[09:18:45.699] Total in 1052 ms
[09:18:45.711] Error: Command "hugo --gc -v --minify --cleanDestinationDir --enableGitInfo" exited with 255

**Comment by Ice-Hazymoon** [comment]
再试试 https://github.com/Ice-Hazymoon/hugo-theme-luna/blob/master/exampleSite/vercel.json ，刚刚测试部署了一下没问题

**Comment by shixiaocaia** [comment]
已解决，谢谢。
